server:
  port: 13093

spring:
  cloud:
    servicecomb:
      discovery:
        enabled: true
        serviceName: ${spring.application.name}
        appName: weathermap
        version: 0.0.3
        watch: false