server:
  port: 13090

spring:
  application:
    name: weather
  cloud:
    servicecomb:
      discovery:
        enabled: true
        address: https://cse.cn-north-1.myhuaweicloud.com
        serviceName: ${spring.application.name}
        appName: weathermap
        version: 0.0.2
        watch: false